# Generated by Django 2.2 on 2019-04-07 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('guid', models.UUIDField(default=uuid.UUID('08a9c511-12cc-4a57-81b3-5b96434c069a'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('guid', models.UUIDField(default=uuid.UUID('11c92b80-6966-4cb7-8d50-7f69fa8f5835'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('founded_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Country')),
            ],
        ),
    ]
